// Mock city configuration
export const cityConfig = {
  id: "1",
  city_name: "Lehi",
  city_state: "Utah",
  city_state_abbr: "UT",
  display_name: "Open Lehi",
  tagline: "Independent Civic Accountability for Lehi, Utah",
  primary_color: "#1a2744",
  accent_color: "#f59e0b",
  logo_url: null,
  city_website: "https://www.lehi-ut.gov",
  population: 75000,
  county: "Utah County",
  timezone: "America/Denver",
  subdomain: "lehi",
  state_domain: "openutah.org",
  state_display_name: "Open Utah",
  full_url: "lehi.openutah.org",
  custom_domain: "openlehi.org",
  email_from: "alerts@openlehi.org",
};

export const mockOfficials = [
  { id: "1", name: "Mark Johnson", slug: "mark-johnson", role: "elected", title: "Mayor", department: "Executive", photo_url: null, bio: "Mayor Mark Johnson has served Lehi since 2020, focusing on responsible growth and infrastructure investment.", social_links: { facebook: "#", website: "#" }, contact_email: "mayor@lehi-ut.gov", status: "active", first_observed: "2020-01-06" },
  { id: "2", name: "Sarah Chen", slug: "sarah-chen", role: "elected", title: "City Council Member", department: "City Council", photo_url: null, bio: "Council Member Chen represents District 1 and chairs the Finance Committee.", social_links: { facebook: "#" }, contact_email: "schen@lehi-ut.gov", status: "active", first_observed: "2022-01-03" },
  { id: "3", name: "David Martinez", slug: "david-martinez", role: "elected", title: "City Council Member", department: "City Council", photo_url: null, bio: "Council Member Martinez represents District 2 with a focus on parks and recreation.", social_links: {}, contact_email: "dmartinez@lehi-ut.gov", status: "active", first_observed: "2022-01-03" },
  { id: "4", name: "Karen Williams", slug: "karen-williams", role: "appointed", title: "City Administrator", department: "Administration", photo_url: null, bio: "Karen Williams oversees day-to-day city operations and has 15 years of municipal management experience.", social_links: {}, contact_email: "kwilliams@lehi-ut.gov", status: "active", first_observed: "2019-06-15" },
  { id: "5", name: "Robert Thompson", slug: "robert-thompson", role: "appointed", title: "Planning Director", department: "Planning Commission", photo_url: null, bio: "Robert Thompson leads the planning department, managing zoning and development review processes.", social_links: {}, contact_email: "rthompson@lehi-ut.gov", status: "active", first_observed: "2018-03-01" },
  { id: "6", name: "Lisa Park", slug: "lisa-park", role: "staff", title: "City Attorney", department: "Legal Department", photo_url: null, bio: "Lisa Park provides legal counsel to the city on development agreements, GRAMA requests, and policy matters.", social_links: {}, contact_email: "lpark@lehi-ut.gov", status: "active", first_observed: "2021-08-15" },
  { id: "7", name: "James Anderson", slug: "james-anderson", role: "appointed", title: "Commission Chair", department: "Planning Commission", photo_url: null, bio: "James Anderson chairs the Planning Commission and reviews all development applications.", social_links: {}, contact_email: "janderson@lehi-ut.gov", status: "active", first_observed: "2020-07-01" },
  { id: "8", name: "Emily Davis", slug: "emily-davis", role: "staff", title: "Finance Director", department: "Finance", photo_url: null, bio: "Emily Davis manages the city's $120M annual budget and financial reporting.", social_links: {}, contact_email: "edavis@lehi-ut.gov", status: "active", first_observed: "2017-01-15" },
];

export const mockMeetings = [
  { id: "1", title: "City Council Regular Session", meeting_date: "2026-03-18T19:00:00", location: "City Hall Council Chambers", meeting_type: "city_council", status: "scheduled", agenda_url: "#", minutes_url: null, packet_url: "#", body: "Regular session of the Lehi City Council." },
  { id: "2", title: "Planning Commission Work Session", meeting_date: "2026-03-20T18:00:00", location: "City Hall Conference Room A", meeting_type: "planning_commission", status: "scheduled", agenda_url: "#", minutes_url: null, packet_url: null, body: "Work session to discuss pending development applications." },
  { id: "3", title: "RDA/CDA Board Meeting", meeting_date: "2026-03-25T17:00:00", location: "City Hall Council Chambers", meeting_type: "rda", status: "scheduled", agenda_url: null, minutes_url: null, packet_url: null, body: "Redevelopment Agency quarterly review." },
  { id: "4", title: "City Council Regular Session", meeting_date: "2026-03-11T19:00:00", location: "City Hall Council Chambers", meeting_type: "city_council", status: "completed", agenda_url: "#", minutes_url: "#", packet_url: "#", body: "Budget amendment discussion and zoning ordinance updates." },
  { id: "5", title: "Public Hearing — Traverse Mountain Phase 4", meeting_date: "2026-03-04T18:30:00", location: "City Hall Council Chambers", meeting_type: "public_hearing", status: "completed", agenda_url: "#", minutes_url: "#", packet_url: "#", body: "Public hearing on the proposed Traverse Mountain Phase 4 development." },
];

export const mockMeetingItems = [
  { id: "1", meeting_id: "1", item_title: "Budget Amendment — Q2 Capital Projects", description: "Proposed $2.3M reallocation for road improvements.", what_is_issue: "The city proposes redirecting $2.3M from general reserves to fund accelerated road repairs on 2100 North and State Street.", legally_current: "This is a new expenditure requiring council approval per municipal code 4.12.", financial_impact: "$2.3M from general fund reserves. Reduces reserve balance to 18% of operating budget (minimum recommended: 15%).", who_benefits: "Residents along 2100 North and State Street corridors. Commuters using these routes daily.", who_harmed: "Projects previously planned for Q3 funding may be delayed. Reserve reduction limits emergency spending capacity.", priority: "high" },
  { id: "2", meeting_id: "1", item_title: "Rezone Request — 400 South Mixed-Use", description: "Developer requesting rezone from R-2 to MU-1.", what_is_issue: "A developer has applied to rezone 12 acres at 400 South from R-2 (residential) to MU-1 (mixed-use) for a 200-unit apartment and retail project.", legally_current: "Requesting a change. Current zoning allows single-family residential only.", financial_impact: "Projected tax revenue increase of $450K/year. Infrastructure costs estimated at $1.8M for road and utility upgrades.", who_benefits: "Developer (increased density = higher ROI). Future residents seeking affordable housing options.", who_harmed: "Adjacent homeowners concerned about traffic, density, and property value impacts. Current residents who purchased expecting R-2 zoning to remain.", priority: "critical" },
];

export const mockIssues = [
  { id: "1", title: "Traverse Mountain Water Pressure Failures", summary: "Residents in Traverse Mountain subdivisions report recurring low water pressure during peak hours, affecting fire safety response capacity.", what_is_issue: "Water infrastructure in upper Traverse Mountain cannot sustain current development density during peak usage.", legally_current: "Requesting change — residents have petitioned for infrastructure upgrades.", financial_impact: "Estimated $4.2M for pump station upgrades. Currently unfunded.", who_benefits: "1,200+ households in affected subdivisions.", who_harmed: "Taxpayers citywide if general fund is used. Developers if impact fees increase.", priority: "critical", category: "utility", status: "open", source_url: "#", created_at: "2026-02-15" },
  { id: "2", title: "Thanksgiving Point Traffic Congestion", summary: "Daily gridlock on 2100 North near Thanksgiving Point during commute hours. Multiple accident reports.", what_is_issue: "Road capacity insufficient for current traffic volumes near the Thanksgiving Point interchange.", legally_current: "UDOT study completed. City has not acted on recommendations.", financial_impact: "$8.5M for proposed interchange improvements. Partial UDOT funding available.", who_benefits: "Commuters, emergency responders, local businesses.", who_harmed: "Properties near proposed road widening. Construction impact on businesses.", priority: "high", category: "development", status: "open", source_url: "#", created_at: "2026-01-20" },
  { id: "3", title: "Planning Commission Quorum Concerns", summary: "Two consecutive meetings cancelled due to lack of quorum. Three commissioner seats remain unfilled for 4+ months.", what_is_issue: "The Planning Commission has operated below full capacity, delaying development reviews.", legally_current: "Current state — appointments are overdue per city ordinance.", financial_impact: "Delayed project approvals cost developers estimated $50K-100K per month in holding costs.", who_benefits: "Residents benefit from thorough review processes when commission is fully staffed.", who_harmed: "Developers with pending applications. Residents waiting for project decisions.", priority: "high", category: "policy", status: "monitoring", source_url: "#", created_at: "2026-02-28" },
  { id: "4", title: "City Attorney GRAMA Response Delays", summary: "Average GRAMA response time has increased to 18 days, exceeding the 10-business-day statutory requirement.", what_is_issue: "The legal department is not meeting GRAMA response deadlines consistently.", legally_current: "Utah Code 63G-2 requires response within 10 business days. City is non-compliant.", financial_impact: "Potential legal liability if residents appeal to State Records Committee.", who_benefits: "City administration benefits from delayed disclosures.", who_harmed: "Residents, journalists, and watchdog organizations seeking public records.", priority: "medium", category: "legal", status: "open", source_url: "#", created_at: "2026-03-01" },
  { id: "5", title: "Lehi Power Rate Increase Proposal", summary: "Lehi Power proposing 8.5% residential rate increase effective July 2026. Public comment period open.", what_is_issue: "Lehi Power seeks to raise residential electricity rates to fund grid modernization.", legally_current: "Requesting change — public hearing scheduled for April 2026.", financial_impact: "Average household impact: +$12/month ($144/year). Total revenue increase: $3.1M.", who_benefits: "Utility operations, grid reliability improvements.", who_harmed: "All residential ratepayers, disproportionate impact on fixed-income households.", priority: "high", category: "utility", status: "open", source_url: "#", created_at: "2026-03-05" },
  { id: "6", title: "Missing Sidewalk Segments on Pioneer Crossing", summary: "Three gaps in sidewalk coverage along Pioneer Crossing near schools, forcing pedestrians onto roadway.", what_is_issue: "Pedestrian safety hazard with missing sidewalk connections near two elementary schools.", legally_current: "Current condition. Identified in 2024 pedestrian safety audit.", financial_impact: "$380K estimated for sidewalk completion. No current budget allocation.", who_benefits: "Students, parents, and pedestrians in the Pioneer Crossing corridor.", who_harmed: "No direct harm from resolution. Risk of injury in current state.", priority: "medium", category: "development", status: "open", source_url: "#", created_at: "2026-02-10" },
];

export const mockDevelopers = [
  { id: "1", applicant_name: "Ivory Homes", project_name: "Traverse Mountain Phase 4", location: "Traverse Mountain Blvd", application_type: "subdivision", status: "active", appearance_count: 7, source_url: "#", notes: "Largest active subdivision application.", created_at: "2025-06-15" },
  { id: "2", applicant_name: "Gardner Company", project_name: "Lehi Station Mixed-Use", location: "400 South & State Street", application_type: "rezone", status: "active", appearance_count: 4, source_url: "#", notes: "Requesting rezone from R-2 to MU-1.", created_at: "2025-11-01" },
  { id: "3", applicant_name: "Suburban Land Reserve", project_name: "Point of the Mountain Development", location: "Point of the Mountain", application_type: "annexation", status: "active", appearance_count: 12, source_url: "#", notes: "Major annexation proposal. State prison relocation site.", created_at: "2024-03-20" },
  { id: "4", applicant_name: "Woodside Homes", project_name: "Holbrook Farms Subdivision", location: "1200 West", application_type: "subdivision", status: "approved", appearance_count: 3, source_url: "#", notes: "Approved with conditions.", created_at: "2025-09-10" },
  { id: "5", applicant_name: "Ivory Homes", project_name: "North Shore Phase 2", location: "2100 North", application_type: "subdivision", status: "active", appearance_count: 5, source_url: "#", notes: "Second phase of North Shore community.", created_at: "2025-07-22" },
  { id: "6", applicant_name: "Mountain Point Development LLC", project_name: "Pioneer Crossing Commercial", location: "Pioneer Crossing & SR-92", application_type: "cup", status: "on_hold", appearance_count: 2, source_url: "#", notes: "Conditional use permit for commercial center.", created_at: "2026-01-15" },
];

export const mockWeeklyReports = [
  { id: "1", week_ending: "2026-03-15", published_at: "2026-03-15T09:00:00", headline: "Water Pressure Crisis Escalates; Council Delays $2.3M Budget Vote", full_content: "This week saw significant developments across multiple fronts...", sections: { top_headlines: ["Water pressure failures reported in 3 additional Traverse Mountain subdivisions", "City Council delays $2.3M budget amendment vote to March 18", "Planning Commission cancels meeting — third quorum failure this quarter"], meetings: "Two meetings held this week. City Council work session focused on utility rate proposals.", council_activity: "Mayor Johnson met with UDOT regarding Thanksgiving Point interchange funding.", development: "Ivory Homes submitted updated Phase 4 plans. Gardner Company rezone hearing postponed.", financial: "Lehi Power rate increase proposal formally submitted. 8.5% residential increase requested.", legal: "City Attorney response times for GRAMA requests remain above statutory limits.", community: "Lehi City Chat: 47 posts about water pressure. Lehi Free Press: editorial on planning commission vacancies.", pending: "Budget amendment vote (March 18). Rezone hearing (March 25). Rate increase public hearing (April 8)." } },
  { id: "2", week_ending: "2026-03-08", published_at: "2026-03-08T09:00:00", headline: "Planning Commission Quorum Crisis; New Development Applications Filed", full_content: "The planning commission's ongoing vacancy crisis continued this week...", sections: { top_headlines: ["Planning Commission meeting cancelled — only 3 of 7 members present", "Two new development applications filed for Pioneer Crossing corridor", "GRAMA response audit reveals 18-day average response time"], meetings: "One meeting held. Planning Commission work session cancelled.", council_activity: "Council Member Chen requests formal audit of GRAMA response compliance.", development: "Two new applications filed. Mountain Point Development LLC applies for CUP.", financial: "Q1 revenue tracking shows property tax collections 3% above projections.", legal: "Legal department acknowledges GRAMA backlog. Requests additional staff funding.", community: "Lehi Link: 23 posts about development density concerns.", pending: "City Council regular session (March 11). Public hearing — Traverse Mountain (March 4)." } },
  { id: "3", week_ending: "2026-03-01", published_at: "2026-03-01T09:00:00", headline: "Traverse Mountain Public Hearing Draws 200+ Residents", full_content: "Over 200 residents attended the public hearing on Traverse Mountain Phase 4...", sections: { top_headlines: ["200+ residents attend Traverse Mountain Phase 4 hearing", "Lehi Power begins formal rate increase process", "City announces sidewalk safety audit results"], meetings: "Public hearing held March 4. City Council regular session March 4.", council_activity: "Full council present. Unanimous vote to commission independent water study.", development: "Traverse Mountain Phase 4 hearing concluded. Decision deferred to March 18.", financial: "Annual financial audit released. Clean opinion with two management letter comments.", legal: "No significant legal activity this week.", community: "Lehi Free Exchange: 67 posts about the Traverse Mountain hearing.", pending: "Planning Commission meeting (March 6). Budget work session (March 10)." } },
];

export const mockCommunityPosts = [
  { id: "1", group_name: "Lehi City Chat", theme: "complaint", summary: "Multiple residents reporting brown water and low pressure in Traverse Mountain. One resident says they've filed 6 complaints in 3 months with no resolution.", source_url: "#", city_response: "no", created_at: "2026-03-13" },
  { id: "2", group_name: "Lehi Free Press", theme: "question", summary: "Why has the Planning Commission been unable to reach quorum for three consecutive meetings? Who is responsible for filling vacant seats?", source_url: "#", city_response: "no", created_at: "2026-03-12" },
  { id: "3", group_name: "Lehi Free Exchange", theme: "development", summary: "Discussion about the proposed 400 South mixed-use rezone. Neighbors concerned about 200-unit apartment density in an R-2 zone.", source_url: "#", city_response: "partial", created_at: "2026-03-10" },
  { id: "4", group_name: "Lehi Link", theme: "utility", summary: "Lehi Power rate increase: residents sharing calculations showing $144/year impact for average household. Asking why rates are rising when city reports surplus.", source_url: "#", city_response: "no", created_at: "2026-03-09" },
  { id: "5", group_name: "Lehi City Chat", theme: "praise", summary: "Residents praising the new trail connection at Dry Creek Park. Several families sharing photos of the completed section.", source_url: "#", city_response: "yes", created_at: "2026-03-08" },
  { id: "6", group_name: "Lehi Free Press", theme: "city_response", summary: "City spokesperson responds to water pressure concerns: 'We are aware of the issue and have commissioned an engineering study expected to be completed by April.'", source_url: "#", city_response: "yes", created_at: "2026-03-07" },
];

export const mockHighPriorityFlags = [
  { id: "1", category: "Infrastructure", summary: "Water pressure below minimum fire safety standards in Traverse Mountain zones 3-5", why_it_matters: "Fire department response capacity is compromised in these areas.", source_url: "#", flagged_at: "2026-03-10", resolved: false },
  { id: "2", category: "Governance", summary: "Planning Commission has not held a quorum meeting in 6 weeks", why_it_matters: "Development applications are accumulating without review, creating a backlog.", source_url: "#", flagged_at: "2026-03-06", resolved: false },
  { id: "3", category: "Compliance", summary: "GRAMA response times exceed statutory 10-day limit", why_it_matters: "The city is not meeting its legal obligations for public records transparency.", source_url: "#", flagged_at: "2026-03-01", resolved: false },
];

export const mockStatements = [
  { id: "1", official_id: "1", statement_date: "2026-03-12", platform: "facebook", content: "Great progress on the Dry Creek trail extension! Looking forward to the ribbon cutting next month.", url: "#" },
  { id: "2", official_id: "1", statement_date: "2026-03-08", platform: "meeting", content: "We need to address the water infrastructure challenges in Traverse Mountain before approving additional density.", url: "#" },
  { id: "3", official_id: "2", statement_date: "2026-03-10", platform: "facebook", content: "I've requested a formal audit of our GRAMA response compliance. Transparency is non-negotiable.", url: "#" },
  { id: "4", official_id: "6", statement_date: "2026-03-05", platform: "meeting", content: "The legal department is working to reduce GRAMA response times. We've requested additional staff in the proposed budget.", url: "#" },
];
